services:
  # Pipeline ML principal
  ml-pipeline:
    build: .
    container_name: nlp-classifier
    
    env_file:
      - .env
    
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./logs:/app/logs
    
    deploy:
      resources:
        limits:
          memory: 4G
    
    networks:
      - monitoring

  # Prometheus (monitoring des métriques)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  # cAdvisor (monitoring des containers)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitoring

  # Node Exporter (métriques système)
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

  # Grafana (visualisation) - PORT CHANGÉ
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"  # CHANGÉ : 3001 au lieu de 3000
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge